[package]
name = "leptos-struct-table"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.2"
leptos-struct-table-macro = "0.1"
paste = "1.0"
async-trait = "0.1"
chrono = "0.4" # TODO : feature flag