[package]
name = "leptos-struct-table"
version = "0.2.0"
edition = "2021"
authors = ["Marc-Stefan Cassola"]
categories = ["gui", "web-programming"]
description = "Generate a complete batteries included leptos data table component from a struct definition."
exclude = ["examples/", "tests/"]
keywords = ["leptos", "table", "data-sheet", "data-grid"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Synphonyte/leptos-struct-table"

[dependencies]
leptos = "0.3"
leptos-struct-table-macro = "0.1"
async-trait = "0.1"
paste = { version = "1.0", optional = true }
chrono = { version = "0.4", optional = true, features = ["serde"] }

[features]
chrono = ["dep:chrono", "dep:paste"]

[dev-dependencies]
serde = "1"

[package.metadata."docs.rs"]
all-features = true
